version: 0.1

phases:
  install:
    commands:
      - npm install bower gulp -g --allow-root
  build:
    commands:
      - npm install
      - bower install --allow-root
      - gulp inject
      - mkdir target
      - zip -r target/multicloud.zip .
artifacts:
  files:
    - target/multicloud.zip
  